version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_DB: DB_NAME
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5445:5432"

  server:
    build:
      context: ./MessagingWebService
      dockerfile: Dockerfile
    ports:
      - "7054:8080"
    depends_on:
      - db
    environment:
      DB_HOST: DB_HOST
      DB_USER: postgres
      DB_PASSWORD: DB_PASSWORD
      DB_NAME: DB_NAME

  clients:
    build: 
      context: ./MessageWebClient
      dockerfile: Dockerfile
    depends_on:
      - server
